image_cols: 640
image_rows: 480
bad_point: 9.9
cv_fs_image_id: "avg_image"
num_images_for_background: 3
person_distance: 1.5
min_distance_near_camera: 0.4
camera_info_topic: /camera_body/depth_registered/camera_info
from_pc2_depth_image_topic: /cv_leg_tracking/from_pc2_depth_image

# default parameters
depth_image_sub_topic: /cv_leg_tracking/from_pc2_depth_image
topic_point_cloud: /camera_legs/depth_registered/points
avg_image_path: background_image/avg_image_legs_camera_cloud.yml

# for comparing purposes, case 1 with body pointcloud
#depth_image_sub_topic: /cv_leg_tracking/from_pc2_depth_image
#topic_point_cloud: /camera_body/depth_registered/points
#avg_image_path: background_image/avg_image_body_camera_cloud.yml

# for comparing purposes, case 2 with body depth image
#depth_image_sub_topic: /camera_body/depth_registered/image_raw
#topic_point_cloud: /camera_body/depth_registered/points
#avg_image_path: background_image/avg_image_body_camera_depth.yml
